name: Publish Package to PyPi

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        # TODO: pin
        run: python -m pip install wheel twine
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: twine upload --repository testpypi dist/*
