name: Publish Package to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: python -m pip install -r .github/workflows/requirements/release.txt
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Check
        run: |
          check-manifest
          twine check dist/*
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: twine upload --repository testpypi dist/*
